### ISSUE TITLE
Message to PilotSchenck

### ISSUE THREAD

**Issue by ghost** [pilotschenck/pilotschenck#2]
Hi, I am not sure if this is intentional or not, but your profile links to a graphic porn site. Did you mistype the URL, or is it intentional?  Sorry or the disturbance. @pilotschenck

**Comment by pilotschenck** [comment]
Thanks -- I had a website which I've let drop a while ago. I removed the link. Thanks for the heads up.

**Comment by ghost** [comment]
@pilotschenck Your Twitter links there too. You might want to take it down.
